export * from './userActions';


export const Action = {
	ERROR: "ERROR",
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	SIGNUP: "SIGNUP",
	PROFILE: "PROFILE",

	LANDING_MODELS: "LANDING_MODELS",
        ADD_MODEL: "ADD_MODEL",
        MODEL_DETAILS: "MODEL_DETAILS",
        DOWNLOAD_MODEL: "DOWNLOAD_MODEL",
	DOWNLOAD_THUMBNAIL: "DOWNLOAD_THUMBNAIL",
	REMOVE_MODEL: "REMOVE_MODEL"	
};
